export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR";
export const SEARCH_USERS_PENDING = "SEARCH_USERS_PENDING";

export const GET_USER_REPO_SUCCESS = "GET_USER_REPO_SUCCESS";
export const GET_USER_REPO_ERROR = "GET_USER_REPO_ERROR";
export const GET_USER_REPO_PENDING = "GET_USER_REPO_PENDING";

export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";
export const GET_USER_PROFILE_PENDING = "GET_USER_PROFILE_PENDING";

export const GET_REPO_READAME_FILE_SUCCESS = "GET_REPO_READAME_FILE_SUCCESS";
export const GET_REPO_READAME_FILE_ERROR = "GET_REPO_READAME_FILE_ERROR";
export const GET_REPO_READAME_FILE_PENDING = "GET_REPO_READAME_FILE_PENDING";
