export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR";
export const SEARCH_USERS_LOADING = "SEARCH_USERS_LOADING";

export const GET_USER_REPO_SUCCESS = "GET_USER_REPO_SUCCESS";
export const GET_USER_REPO_ERROR = "GET_USER_REPO_ERROR";
export const GET_USER_REPO_LOADING = "GET_USER_REPO_LOADING";

export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";
export const GET_USER_PROFILE_LOADING = "GET_USER_PROFILE_LOADING";

export const GET_REPO_READAME_FILE_SUCCESS = "GET_REPO_READAME_FILE_SUCCESS";
export const GET_REPO_READAME_FILE_ERROR = "GET_REPO_READAME_FILE_ERROR";
export const GET_REPO_READAME_FILE_LOADING = "GET_REPO_READAME_FILE_LOADING";
